language: node_js
node_js:
- node
addons:
  sshknownhosts: 206.189.96.128
branches:
  only:
  - develop
  - travis
before_install:
- openssl aes-256-cbc -K $encrypted_47ecb0011c7b_key -iv $encrypted_47ecb0011c7b_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 ~/.ssh/authorized_keys
install:
- npm i
script:
 - npm run test
 - npm run build
#deploy:
 # skip_cleanup: true
  #provider: script
  #script: .scripts/deploy.sh
  #on:
   # all_branches: true
    #condition: $TRAVIS_BRANCH =~ ^travis|develop$
