language: node_js
node_js:
- "10"
addons:
  ssh_known_hosts: 
  - 206.189.96.128
  - recipemug.club
branches:
  only:
  - develop
  - travis
env:
  global:
  - REMOTE_APPDIR=/var/www/new.recipemug.club/
  - REMOTE_USER=travis
  - REMOTE_HOST=206.189.96.128 # your droplet IP goes here
  #- PORT=8080
before_install:
- openssl aes-256-cbc -K $encrypted_47ecb0011c7b_key -iv $encrypted_47ecb0011c7b_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
install:
- npm i
script:
 - npm run test
 - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash .scripts/deploy.sh
  on:
    branch: travis
    #all_branches: true
    #condition: $TRAVIS_BRANCH =~ ^travis|develop$
notifications: 
  email: false
